#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.6
# from Racc grammer file "".
#

require 'racc/parser.rb'

  require "lexer"
  require "nodes"

class Parser < Racc::Parser

module_eval(<<'...end grammar.y/module_eval...', 'grammar.y', 179)
  # This code will be put as-is in the Parser class.
  def parse(code, show_tokens=false)
    @tokens = Lexer.new.tokenize(code) # Tokenize the code using our lexer
    puts @tokens.inspect if show_tokens
    do_parse # Kickoff the parsing process
  end
  
  def next_token
    @tokens.shift
  end
...end grammar.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    27,    15,    28,    25,    26,    15,    17,    18,    19,    20,
    21,    22,    24,    15,    27,    23,    28,    25,    26,    15,
    17,    18,    19,    20,    21,    22,    24,    85,    16,    23,
    14,    15,    16,    31,    31,    42,    43,    40,    41,    31,
    16,    42,    43,    31,    14,    27,    16,    28,    25,    26,
    83,    17,    18,    19,    20,    21,    22,    24,    16,    27,
    23,    28,    25,    26,    49,    17,    18,    19,    20,    21,
    22,    24,    48,    31,    23,    14,    27,    79,    28,    25,
    26,    50,    17,    18,    19,    20,    21,    22,    24,    14,
    27,    23,    28,    25,    26,    53,    17,    18,    19,    20,
    21,    22,    24,    55,    29,    23,    14,    27,    93,    28,
    25,    26,   nil,    17,    18,    19,    20,    21,    22,    24,
    14,    27,    23,    28,    25,    26,   nil,    17,    18,    19,
    20,    21,    22,    24,   nil,   nil,    23,    14,    27,   nil,
    28,    25,    26,   nil,    17,    18,    19,    20,    21,    22,
    24,    14,    27,    23,    28,    25,    26,   nil,    17,    18,
    19,    20,    21,    22,    24,   nil,   nil,    23,    14,    27,
   nil,    28,    25,    26,   nil,    17,    18,    19,    20,    21,
    22,    24,    14,    27,    23,    28,    25,    26,   nil,    17,
    18,    19,    20,    21,    22,    24,   nil,   nil,    23,    14,
    27,   nil,    28,    25,    26,   nil,    17,    18,    19,    20,
    21,    22,    24,    14,    27,    23,    28,    25,    26,   nil,
    17,    18,    19,    20,    21,    22,    24,   nil,   nil,    23,
    14,    27,   nil,    28,    25,    26,   nil,    17,    18,    19,
    20,    21,    22,    24,    14,    27,    23,    28,    25,    26,
   nil,    17,    18,    19,    20,    21,    22,    24,   nil,   nil,
    23,    14,    27,   nil,    28,    25,    26,   nil,    17,    18,
    19,    20,    21,    22,    24,    14,    27,    23,    28,    25,
    26,   nil,    17,    18,    19,    20,    21,    22,    24,   nil,
   nil,    23,    14,    27,   nil,    28,    25,    26,   nil,    17,
    18,    19,    20,    21,    22,    24,    14,    27,    23,    28,
    25,    26,   nil,    17,    18,    19,    20,    21,    22,    24,
   nil,   nil,    23,    14,    27,   nil,    28,    25,    26,   nil,
    17,    18,    19,    20,    21,    22,    24,    14,    27,    23,
    28,    25,    26,   nil,    17,    18,    19,    20,    21,    22,
    24,   nil,   nil,    23,    14,    27,   nil,    28,    25,    26,
   nil,    17,    18,    19,    20,    21,    22,    24,    14,    27,
    23,    28,    25,    26,   nil,    17,    18,    19,    20,    21,
    22,    24,   nil,   nil,    23,    14,    15,   nil,   nil,    15,
    15,   nil,   nil,    31,    90,    42,    43,   nil,    31,    14,
    42,    43,    40,    41,    36,    37,    38,    39,    34,    35,
    33,    32,    15,    16,   nil,    74,    16,    16,    89,   nil,
    88,    31,   nil,    42,    43,    40,    41,    36,    37,    38,
    39,    34,    35,    33,    32,    81,   nil,    91,    31,    16,
    42,    43,    40,    41,    36,    37,    38,    39,    34,    35,
    33,    32,   nil,   nil,    31,    68,    42,    43,    40,    41,
    36,    37,    38,    39,    34,    35,    33,    32,    31,   nil,
    42,    43,    40,    41,    36,    37,    38,    39,    34,    35,
    33,    32,    31,   nil,    42,    43,    40,    41,    36,    37,
    38,    39,    34,    35,    33,    32,    31,   nil,    42,    43,
    40,    41,    36,    37,    38,    39,    34,    35,    33,    32,
    31,   nil,    42,    43,    40,    41,    36,    37,    38,    39,
    34,    35,    33,    32,    31,   nil,    42,    43,    40,    41,
    36,    37,    38,    39,    34,    35,    33,    32,    31,   nil,
    42,    43,    40,    41,    36,    37,    38,    39,    34,    35,
    33,    31,   nil,    42,    43,    40,    41,    36,    37,    38,
    39,    34,    35,    31,   nil,    42,    43,    40,    41,    36,
    37,    38,    39,    31,   nil,    42,    43,    40,    41,    36,
    37,    38,    39,    31,   nil,    42,    43,    40,    41,    31,
   nil,    42,    43,    40,    41,    31,   nil,    42,    43,    40,
    41,    81,    46,    80,    45 ]

racc_action_check = [
     0,     2,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,    50,    75,     0,    75,    75,    75,    75,
    75,    75,    75,    75,    75,    75,    75,    75,     2,    75,
     0,    88,     0,    60,    47,    60,    60,    60,    60,    64,
    50,    64,    64,    66,    75,    32,    75,    32,    32,    32,
    74,    32,    32,    32,    32,    32,    32,    32,    88,    46,
    32,    46,    46,    46,    25,    46,    46,    46,    46,    46,
    46,    46,    24,    67,    46,    32,    14,    55,    14,    14,
    14,    26,    14,    14,    14,    14,    14,    14,    14,    46,
    81,    14,    81,    81,    81,    29,    81,    81,    81,    81,
    81,    81,    81,    31,     1,    81,    14,    23,    89,    23,
    23,    23,   nil,    23,    23,    23,    23,    23,    23,    23,
    81,    79,    23,    79,    79,    79,   nil,    79,    79,    79,
    79,    79,    79,    79,   nil,   nil,    79,    23,    45,   nil,
    45,    45,    45,   nil,    45,    45,    45,    45,    45,    45,
    45,    79,    48,    45,    48,    48,    48,   nil,    48,    48,
    48,    48,    48,    48,    48,   nil,   nil,    48,    45,    27,
   nil,    27,    27,    27,   nil,    27,    27,    27,    27,    27,
    27,    27,    48,    28,    27,    28,    28,    28,   nil,    28,
    28,    28,    28,    28,    28,    28,   nil,   nil,    28,    27,
    43,   nil,    43,    43,    43,   nil,    43,    43,    43,    43,
    43,    43,    43,    28,    30,    43,    30,    30,    30,   nil,
    30,    30,    30,    30,    30,    30,    30,   nil,   nil,    30,
    43,    42,   nil,    42,    42,    42,   nil,    42,    42,    42,
    42,    42,    42,    42,    30,    41,    42,    41,    41,    41,
   nil,    41,    41,    41,    41,    41,    41,    41,   nil,   nil,
    41,    42,    40,   nil,    40,    40,    40,   nil,    40,    40,
    40,    40,    40,    40,    40,    41,    34,    40,    34,    34,
    34,   nil,    34,    34,    34,    34,    34,    34,    34,   nil,
   nil,    34,    40,    35,   nil,    35,    35,    35,   nil,    35,
    35,    35,    35,    35,    35,    35,    34,    36,    35,    36,
    36,    36,   nil,    36,    36,    36,    36,    36,    36,    36,
   nil,   nil,    36,    35,    37,   nil,    37,    37,    37,   nil,
    37,    37,    37,    37,    37,    37,    37,    36,    38,    37,
    38,    38,    38,   nil,    38,    38,    38,    38,    38,    38,
    38,   nil,   nil,    38,    37,    39,   nil,    39,    39,    39,
   nil,    39,    39,    39,    39,    39,    39,    39,    38,    33,
    39,    33,    33,    33,   nil,    33,    33,    33,    33,    33,
    33,    33,   nil,   nil,    33,    39,    84,   nil,   nil,    51,
    49,   nil,   nil,    65,    84,    65,    65,   nil,    51,    33,
    51,    51,    51,    51,    51,    51,    51,    51,    51,    51,
    51,    51,    52,    84,   nil,    49,    51,    49,    82,   nil,
    82,    52,   nil,    52,    52,    52,    52,    52,    52,    52,
    52,    52,    52,    52,    52,    86,   nil,    86,    44,    52,
    44,    44,    44,    44,    44,    44,    44,    44,    44,    44,
    44,    44,   nil,   nil,    71,    44,    71,    71,    71,    71,
    71,    71,    71,    71,    71,    71,    71,    71,    87,   nil,
    87,    87,    87,    87,    87,    87,    87,    87,    87,    87,
    87,    87,    70,   nil,    70,    70,    70,    70,    70,    70,
    70,    70,    70,    70,    70,    70,     3,   nil,     3,     3,
     3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
    72,   nil,    72,    72,    72,    72,    72,    72,    72,    72,
    72,    72,    72,    72,    54,   nil,    54,    54,    54,    54,
    54,    54,    54,    54,    54,    54,    54,    54,    56,   nil,
    56,    56,    56,    56,    56,    56,    56,    56,    56,    56,
    56,    57,   nil,    57,    57,    57,    57,    57,    57,    57,
    57,    57,    57,    58,   nil,    58,    58,    58,    58,    58,
    58,    58,    58,    59,   nil,    59,    59,    59,    59,    59,
    59,    59,    59,    61,   nil,    61,    61,    61,    61,    63,
   nil,    63,    63,    63,    63,    62,   nil,    62,    62,    62,
    62,    69,    22,    69,    22 ]

racc_action_pointer = [
    -2,   104,    -6,   480,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    74,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   572,   105,    42,    51,    67,   167,   181,    95,
   212,    90,    43,   367,   274,   291,   305,   322,   336,   353,
   260,   243,   229,   198,   422,   136,    57,    18,   150,   383,
     6,   382,   405,   nil,   508,    45,   522,   535,   547,   557,
    17,   567,   579,   573,    23,   377,    27,    57,   nil,   570,
   466,   438,   494,   nil,    37,    12,   nil,   nil,   nil,   119,
   nil,    88,   387,   nil,   379,   nil,   404,   452,    24,    95,
   nil,   nil,   nil,   nil ]

racc_action_default = [
    -1,   -57,    -2,    -3,    -6,    -7,    -8,    -9,   -10,   -11,
   -12,   -13,   -14,   -15,   -57,   -17,   -18,   -19,   -20,   -21,
   -22,   -23,   -24,   -57,   -44,   -57,   -57,   -57,   -57,   -57,
    -5,   -57,   -57,   -57,   -57,   -57,   -57,   -57,   -57,   -57,
   -57,   -57,   -57,   -57,   -57,   -28,   -57,   -43,   -57,   -57,
   -57,   -57,   -57,    94,    -4,   -26,   -31,   -32,   -33,   -34,
   -35,   -36,   -37,   -38,   -39,   -40,   -41,   -42,   -16,   -57,
   -29,   -45,   -46,   -47,   -49,   -57,   -52,   -53,   -54,   -28,
   -25,   -57,   -57,   -50,   -57,   -56,   -57,   -30,   -57,   -57,
   -55,   -27,   -48,   -51 ]

racc_goto_table = [
     4,     2,    30,    44,    73,    76,    77,    78,    69,     1,
    82,   nil,    47,   nil,   nil,   nil,    51,    52,   nil,    54,
   nil,    56,    57,    58,    59,    60,    61,    62,    63,    64,
    65,    66,    67,   nil,    70,    71,   nil,    72,   nil,   nil,
   nil,   nil,    86,    92,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    70,   nil,
    87,   nil,   nil,   nil,   nil,     4,    84,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    30 ]

racc_goto_check = [
     4,     2,     4,     3,    15,    15,    15,    15,    14,     1,
    16,   nil,     3,   nil,   nil,   nil,     3,     3,   nil,     3,
   nil,     3,     3,     3,     3,     3,     3,     3,     3,     3,
     3,     3,     3,   nil,     3,     3,   nil,     3,   nil,   nil,
   nil,   nil,    14,    15,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     3,   nil,
     3,   nil,   nil,   nil,   nil,     4,     2,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,     4 ]

racc_goto_pointer = [
   nil,     9,     1,   -11,     0,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   -37,   -45,   -64 ]

racc_goto_default = [
   nil,   nil,   nil,     3,    75,     5,     6,     7,     8,     9,
    10,    11,    12,    13,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  0, 36, :_reduce_1,
  1, 36, :_reduce_2,
  1, 37, :_reduce_3,
  3, 37, :_reduce_4,
  2, 37, :_reduce_5,
  1, 37, :_reduce_6,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  3, 38, :_reduce_16,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  1, 40, :_reduce_19,
  1, 40, :_reduce_20,
  1, 40, :_reduce_21,
  1, 40, :_reduce_22,
  1, 40, :_reduce_23,
  1, 41, :_reduce_24,
  4, 41, :_reduce_25,
  3, 41, :_reduce_26,
  6, 41, :_reduce_27,
  0, 49, :_reduce_28,
  1, 49, :_reduce_29,
  3, 49, :_reduce_30,
  3, 42, :_reduce_31,
  3, 42, :_reduce_32,
  3, 42, :_reduce_33,
  3, 42, :_reduce_34,
  3, 42, :_reduce_35,
  3, 42, :_reduce_36,
  3, 42, :_reduce_37,
  3, 42, :_reduce_38,
  3, 42, :_reduce_39,
  3, 42, :_reduce_40,
  3, 42, :_reduce_41,
  3, 42, :_reduce_42,
  2, 42, :_reduce_43,
  1, 43, :_reduce_44,
  3, 44, :_reduce_45,
  3, 44, :_reduce_46,
  3, 45, :_reduce_47,
  6, 45, :_reduce_48,
  0, 51, :_reduce_49,
  1, 51, :_reduce_50,
  3, 51, :_reduce_51,
  3, 46, :_reduce_52,
  3, 47, :_reduce_53,
  3, 48, :_reduce_54,
  3, 50, :_reduce_55,
  2, 50, :_reduce_56 ]

racc_reduce_n = 57

racc_shift_n = 94

racc_token_table = {
  false => 0,
  :error => 1,
  :IF => 2,
  :ELSE => 3,
  :WHILE => 4,
  :MATEY => 5,
  :SHIP => 6,
  :NEWLINE => 7,
  :NUMBER => 8,
  :STRING => 9,
  :TRUE => 10,
  :FALSE => 11,
  :NIL => 12,
  :IDENTIFIER => 13,
  :CONSTANT => 14,
  :ENDS => 15,
  "." => 16,
  "!" => 17,
  "*" => 18,
  "/" => 19,
  "+" => 20,
  "-" => 21,
  ">" => 22,
  ">=" => 23,
  "<" => 24,
  "<=" => 25,
  "==" => 26,
  "!=" => 27,
  "&&" => 28,
  "||" => 29,
  "=" => 30,
  "," => 31,
  "(" => 32,
  ")" => 33,
  ";" => 34 }

racc_nt_base = 35

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "IF",
  "ELSE",
  "WHILE",
  "MATEY",
  "SHIP",
  "NEWLINE",
  "NUMBER",
  "STRING",
  "TRUE",
  "FALSE",
  "NIL",
  "IDENTIFIER",
  "CONSTANT",
  "ENDS",
  "\".\"",
  "\"!\"",
  "\"*\"",
  "\"/\"",
  "\"+\"",
  "\"-\"",
  "\">\"",
  "\">=\"",
  "\"<\"",
  "\"<=\"",
  "\"==\"",
  "\"!=\"",
  "\"&&\"",
  "\"||\"",
  "\"=\"",
  "\",\"",
  "\"(\"",
  "\")\"",
  "\";\"",
  "$start",
  "Root",
  "Expressions",
  "Expression",
  "Terminator",
  "Literal",
  "Call",
  "Operator",
  "Constant",
  "Assign",
  "Def",
  "Class",
  "If",
  "While",
  "ArgList",
  "Block",
  "ParamList" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'grammar.y', 45)
  def _reduce_1(val, _values, result)
     result = Nodes.new([]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 46)
  def _reduce_2(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 51)
  def _reduce_3(val, _values, result)
     result = Nodes.new(val) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 52)
  def _reduce_4(val, _values, result)
     result = val[0] << val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 54)
  def _reduce_5(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 55)
  def _reduce_6(val, _values, result)
     result = Nodes.new([]) 
    result
  end
.,.,

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

module_eval(<<'.,.,', 'grammar.y', 69)
  def _reduce_16(val, _values, result)
     result = val[1] 
    result
  end
.,.,

# reduce 17 omitted

# reduce 18 omitted

module_eval(<<'.,.,', 'grammar.y', 80)
  def _reduce_19(val, _values, result)
     result = NumberNode.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 81)
  def _reduce_20(val, _values, result)
     result = StringNode.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 82)
  def _reduce_21(val, _values, result)
     result = TrueNode.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 83)
  def _reduce_22(val, _values, result)
     result = FalseNode.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 84)
  def _reduce_23(val, _values, result)
     result = NilNode.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 90)
  def _reduce_24(val, _values, result)
     result = CallNode.new(nil, val[0], []) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 92)
  def _reduce_25(val, _values, result)
     result = CallNode.new(nil, val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 94)
  def _reduce_26(val, _values, result)
     result = CallNode.new(val[0], val[2], []) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 97)
  def _reduce_27(val, _values, result)
     result = CallNode.new(val[0], val[2], val[4]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 101)
  def _reduce_28(val, _values, result)
     result = [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 102)
  def _reduce_29(val, _values, result)
     result = val 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 103)
  def _reduce_30(val, _values, result)
     result = val[0] << val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 108)
  def _reduce_31(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 109)
  def _reduce_32(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 110)
  def _reduce_33(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 111)
  def _reduce_34(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 112)
  def _reduce_35(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 113)
  def _reduce_36(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 114)
  def _reduce_37(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 115)
  def _reduce_38(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 116)
  def _reduce_39(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 117)
  def _reduce_40(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 118)
  def _reduce_41(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 119)
  def _reduce_42(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 120)
  def _reduce_43(val, _values, result)
     result = CallNode.new(val[1], val[0], []) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 124)
  def _reduce_44(val, _values, result)
     result = GetConstantNode.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 129)
  def _reduce_45(val, _values, result)
     result = SetLocalNode.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 130)
  def _reduce_46(val, _values, result)
     result = SetConstantNode.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 135)
  def _reduce_47(val, _values, result)
     result = DefNode.new(val[1], [], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 137)
  def _reduce_48(val, _values, result)
     result = DefNode.new(val[1], val[3], val[5]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 141)
  def _reduce_49(val, _values, result)
     result = [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 142)
  def _reduce_50(val, _values, result)
     result = val 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 143)
  def _reduce_51(val, _values, result)
     result = val[0] << val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 148)
  def _reduce_52(val, _values, result)
     result = ClassNode.new(val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 153)
  def _reduce_53(val, _values, result)
     result = IfNode.new(val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 158)
  def _reduce_54(val, _values, result)
     result = WhileNode.new(val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 164)
  def _reduce_55(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 165)
  def _reduce_56(val, _values, result)
     result = [] 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class Parser
